import { MenuItem, Select } from "@mui/material"

export default function GetCountryList(props: any) {


    return (
        <Select
            fullWidth
            placeholder='Country'
            label='Article Country'
            labelId='Country'
            defaultValue={props.country}
            onChange={e => { props.setCountry(e.target.value) }}
        >
            <MenuItem value='Afghanistan'>Afghanistan</MenuItem>
            <MenuItem value='Albania'>Albania</MenuItem>
            <MenuItem value='Algeria'>Algeria</MenuItem>
            <MenuItem value='Andorra'>Andorra</MenuItem>
            <MenuItem value='Angola'>Angola</MenuItem>
            <MenuItem value='Anguilla'>Anguilla</MenuItem>
            <MenuItem value='Antigua & Barbuda'>Antigua & Barbuda</MenuItem>
            <MenuItem value='Argentina'>Argentina</MenuItem>
            <MenuItem value='Armenia'>Armenia</MenuItem>
            <MenuItem value='Australia'>Australia</MenuItem>
            <MenuItem value='Austria'>Austria</MenuItem>
            <MenuItem value='Azerbaijan'>Azerbaijan</MenuItem>
            <MenuItem value='Bahamas'>Bahamas</MenuItem>
            <MenuItem value='Bahrain'>Bahrain</MenuItem>
            <MenuItem value='Bangladesh'>Bangladesh</MenuItem>
            <MenuItem value='Barbados'>Barbados</MenuItem>
            <MenuItem value='Belarus'>Belarus</MenuItem>
            <MenuItem value='Belgium'>Belgium</MenuItem>
            <MenuItem value='Belize'>Belize</MenuItem>
            <MenuItem value='Benin'>Benin</MenuItem>
            <MenuItem value='Bermuda'>Bermuda</MenuItem>
            <MenuItem value='Bhutan'>Bhutan</MenuItem>
            <MenuItem value='Bolivia'>Bolivia</MenuItem>
            <MenuItem value='Bosnia & Herzegovina'>Bosnia & Herzegovina</MenuItem>
            <MenuItem value='Botswana'>Botswana</MenuItem>
            <MenuItem value='Brazil'>Brazil</MenuItem>
            <MenuItem value='Brunei Darussalam'>Brunei Darussalam</MenuItem>
            <MenuItem value='Bulgaria'>Bulgaria</MenuItem>
            <MenuItem value='Burkina Faso'>Burkina Faso</MenuItem>
            <MenuItem value='Burundi'>Burundi</MenuItem>
            <MenuItem value='Cambodia'>Cambodia</MenuItem>
            <MenuItem value='Cameroon'>Cameroon</MenuItem>
            <MenuItem value='Canada'>Canada</MenuItem>
            <MenuItem value='Cape Verde'>Cape Verde</MenuItem>
            <MenuItem value='Cayman Islands'>Cayman Islands</MenuItem>
            <MenuItem value='Central African Republic'>Central African Republic</MenuItem>
            <MenuItem value='Chad'>Chad</MenuItem>
            <MenuItem value='Chile'>Chile</MenuItem>
            <MenuItem value='China'>China</MenuItem>
            <MenuItem value='China - Hong Kong / Macau'>China - Hong Kong / Macau</MenuItem>
            <MenuItem value='Colombia'>Colombia</MenuItem>
            <MenuItem value='Comoros'>Comoros</MenuItem>
            <MenuItem value='Congo'>Congo</MenuItem>
            <MenuItem value='Congo, Democratic Republic of (DRC)'>Congo, Democratic Republic of (DRC)</MenuItem>
            <MenuItem value='Costa Rica'>Costa Rica</MenuItem>
            <MenuItem value='Croatia'>Croatia</MenuItem>
            <MenuItem value='Cuba'>Cuba</MenuItem>
            <MenuItem value='Cyprus'>Cyprus</MenuItem>
            <MenuItem value='Czech Republic'>Czech Republic</MenuItem>
            <MenuItem value='Denmark'>Denmark</MenuItem>
            <MenuItem value='Djibouti'>Djibouti</MenuItem>
            <MenuItem value='Dominica'>Dominica</MenuItem>
            <MenuItem value='Dominican Republic'>Dominican Republic</MenuItem>
            <MenuItem value='Ecuador'>Ecuador</MenuItem>
            <MenuItem value='Egypt'>Egypt</MenuItem>
            <MenuItem value='El Salvador'>El Salvador</MenuItem>
            <MenuItem value='Equatorial Guinea'>Equatorial Guinea</MenuItem>
            <MenuItem value='Eritrea'>Eritrea</MenuItem>
            <MenuItem value='Estonia'>Estonia</MenuItem>
            <MenuItem value='Eswatini'>Eswatini</MenuItem>
            <MenuItem value='Ethiopia'>Ethiopia</MenuItem>
            <MenuItem value='Fiji'>Fiji</MenuItem>
            <MenuItem value='Finland'>Finland</MenuItem>
            <MenuItem value='France'>France</MenuItem>
            <MenuItem value='French Guiana'>French Guiana</MenuItem>
            <MenuItem value='Gabon'>Gabon</MenuItem>
            <MenuItem value='Gambia, Republic of The'>Gambia, Republic of The</MenuItem>
            <MenuItem value='Georgia'>Georgia</MenuItem>
            <MenuItem value='Germany'>Germany</MenuItem>
            <MenuItem value='Ghana'>Ghana</MenuItem>
            <MenuItem value='Great Britain'>Great Britain</MenuItem>
            <MenuItem value='Greece'>Greece</MenuItem>
            <MenuItem value='Grenada'>Grenada</MenuItem>
            <MenuItem value='Guadeloupe'>Guadeloupe</MenuItem>
            <MenuItem value='Guatemala'>Guatemala</MenuItem>
            <MenuItem value='Guinea'>Guinea</MenuItem>
            <MenuItem value='Guinea-Bissau'>Guinea-Bissau</MenuItem>
            <MenuItem value='Guyana'>Guyana</MenuItem>
            <MenuItem value='Haiti'>Haiti</MenuItem>
            <MenuItem value='Honduras'>Honduras</MenuItem>
            <MenuItem value='Hungary'>Hungary</MenuItem>
            <MenuItem value='Iceland'>Iceland</MenuItem>
            <MenuItem value='India'>India</MenuItem>
            <MenuItem value='Indonesia'>Indonesia</MenuItem>
            <MenuItem value='Iran'>Iran</MenuItem>
            <MenuItem value='Iraq'>Iraq</MenuItem>
            <MenuItem value='Israel and the Occupied Territories'>Israel and the Occupied Territories</MenuItem>
            <MenuItem value='Italy'>Italy</MenuItem>
            <MenuItem value="Ivory Coast (Cote d'Ivoire)">Ivory Coast (Cote d'Ivoire)</MenuItem>
            <MenuItem value='Jamaica'>Jamaica</MenuItem>
            <MenuItem value='Japan'>Japan</MenuItem>
            <MenuItem value='Jordan'>Jordan</MenuItem>
            <MenuItem value='Kazakhstan'>Kazakhstan</MenuItem>
            <MenuItem value='Kenya'>Kenya</MenuItem>
            <MenuItem value='Korea, Democratic Republic of (North Korea)'>Korea, Democratic Republic of (North Korea)</MenuItem>
            <MenuItem value='Korea, Republic of (South Korea)'>Korea, Republic of (South Korea)</MenuItem>
            <MenuItem value='Kosovo'>Kosovo</MenuItem>
            <MenuItem value='Kuwait'>Kuwait</MenuItem>
            <MenuItem value='Kyrgyz Republic (Kyrgyzstan)'>Kyrgyz Republic (Kyrgyzstan)</MenuItem>
            <MenuItem value='Laos'>Laos</MenuItem>
            <MenuItem value='Latvia'>Latvia</MenuItem>
            <MenuItem value='Lebanon'>Lebanon</MenuItem>
            <MenuItem value='Lesotho'>Lesotho</MenuItem>
            <MenuItem value='Liberia'>Liberia</MenuItem>
            <MenuItem value='Libya'>Libya</MenuItem>
            <MenuItem value='Liechtenstein'>Liechtenstein</MenuItem>
            <MenuItem value='Lithuania'>Lithuania</MenuItem>
            <MenuItem value='Luxembourg'>Luxembourg</MenuItem>
            <MenuItem value='Madagascar'>Madagascar</MenuItem>
            <MenuItem value='Malawi'>Malawi</MenuItem>
            <MenuItem value='Malaysia'>Malaysia</MenuItem>
            <MenuItem value='Maldives'>Maldives</MenuItem>
            <MenuItem value='Mali'>Mali</MenuItem>
            <MenuItem value='Malta'>Malta</MenuItem>
            <MenuItem value='Martinique'>Martinique</MenuItem>
            <MenuItem value='Mauritania'>Mauritania</MenuItem>
            <MenuItem value='Mauritius'>Mauritius</MenuItem>
            <MenuItem value='Mayotte'>Mayotte</MenuItem>
            <MenuItem value='Mexico'>Mexico</MenuItem>
            <MenuItem value='Moldova, Republic of'>Moldova, Republic of</MenuItem>
            <MenuItem value='Monaco'>Monaco</MenuItem>
            <MenuItem value='Mongolia'>Mongolia</MenuItem>
            <MenuItem value='Montenegro'>Montenegro</MenuItem>
            <MenuItem value='Montserrat'>Montserrat</MenuItem>
            <MenuItem value='Morocco'>Morocco</MenuItem>
            <MenuItem value='Mozambique'>Mozambique</MenuItem>
            <MenuItem value='Myanmar/Burma'>Myanmar/Burma</MenuItem>
            <MenuItem value='Namibia'>Namibia</MenuItem>
            <MenuItem value='Nepal'>Nepal</MenuItem>
            <MenuItem value='Netherlands'>Netherlands</MenuItem>
            <MenuItem value='New Zealand'>New Zealand</MenuItem>
            <MenuItem value='Nicaragua'>Nicaragua</MenuItem>
            <MenuItem value='Niger'>Niger</MenuItem>
            <MenuItem value='Nigeria'>Nigeria</MenuItem>
            <MenuItem value='North Macedonia, Republic of'>North Macedonia, Republic of</MenuItem>
            <MenuItem value='Norway'>Norway</MenuItem>
            <MenuItem value='Oman'>Oman</MenuItem>
            <MenuItem value='Pacific Islands'>Pacific Islands</MenuItem>
            <MenuItem value='Pakistan'>Pakistan</MenuItem>
            <MenuItem value='Panama'>Panama</MenuItem>
            <MenuItem value='Papua New Guinea'>Papua New Guinea</MenuItem>
            <MenuItem value='Paraguay'>Paraguay</MenuItem>
            <MenuItem value='Peru'>Peru</MenuItem>
            <MenuItem value='Philippines'>Philippines</MenuItem>
            <MenuItem value='Poland'>Poland</MenuItem>
            <MenuItem value='Portugal'>Portugal</MenuItem>
            <MenuItem value='Puerto Rico'>Puerto Rico</MenuItem>
            <MenuItem value='Qatar'>Qatar</MenuItem>
            <MenuItem value='Reunion'>Reunion</MenuItem>
            <MenuItem value='Romania'>Romania</MenuItem>
            <MenuItem value='Russian Federation'>Russian Federation</MenuItem>
            <MenuItem value='Rwanda'>Rwanda</MenuItem>
            <MenuItem value='Saint Kitts and Nevis'>Saint Kitts and Nevis</MenuItem>
            <MenuItem value='Saint Lucia'>Saint Lucia</MenuItem>
            <MenuItem value='Saint Vincent and the Grenadines'>Saint Vincent and the Grenadines</MenuItem>
            <MenuItem value='Samoa'>Samoa</MenuItem>
            <MenuItem value='Sao Tome and Principe'>Sao Tome and Principe</MenuItem>
            <MenuItem value='Saudi Arabia'>Saudi Arabia</MenuItem>
            <MenuItem value='Senegal'>Senegal</MenuItem>
            <MenuItem value='Serbia'>Serbia</MenuItem>
            <MenuItem value='Seychelles'>Seychelles</MenuItem>
            <MenuItem value='Sierra Leone'>Sierra Leone</MenuItem>
            <MenuItem value='Singapore'>Singapore</MenuItem>
            <MenuItem value='Slovak Republic (Slovakia)'>Slovak Republic (Slovakia)</MenuItem>
            <MenuItem value='Slovenia'>Slovenia</MenuItem>
            <MenuItem value='Solomon Islands'>Solomon Islands</MenuItem>
            <MenuItem value='Somalia'>Somalia</MenuItem>
            <MenuItem value='South Africa'>South Africa</MenuItem>
            <MenuItem value='South Sudan'>South Sudan</MenuItem>
            <MenuItem value='Spain'>Spain</MenuItem>
            <MenuItem value='Sri Lanka'>Sri Lanka</MenuItem>
            <MenuItem value='Sudan'>Sudan</MenuItem>
            <MenuItem value='Suriname'>Suriname</MenuItem>
            <MenuItem value='Sweden'>Sweden</MenuItem>
            <MenuItem value='Switzerland'>Switzerland</MenuItem>
            <MenuItem value='Syria'>Syria</MenuItem>
            <MenuItem value='Tajikistan'>Tajikistan</MenuItem>
            <MenuItem value='Tanzania'>Tanzania</MenuItem>
            <MenuItem value='Thailand'>Thailand</MenuItem>
            <MenuItem value='Timor Leste'>Timor Leste</MenuItem>
            <MenuItem value='Togo'>Togo</MenuItem>
            <MenuItem value='Trinidad & Tobago'>Trinidad & Tobago</MenuItem>
            <MenuItem value='Tunisia'>Tunisia</MenuItem>
            <MenuItem value='Türkiye (Turkey)'>Türkiye (Turkey)</MenuItem>
            <MenuItem value='Turkmenistan'>Turkmenistan</MenuItem>
            <MenuItem value='Turks & Caicos Islands'>Turks & Caicos Islands</MenuItem>
            <MenuItem value='Uganda'>Uganda</MenuItem>
            <MenuItem value='Ukraine'>Ukraine</MenuItem>
            <MenuItem value='United Arab Emirates'>United Arab Emirates</MenuItem>
            <MenuItem value='United States of America (USA)'>United States of America (USA)</MenuItem>
            <MenuItem value='Uruguay'>Uruguay</MenuItem>
            <MenuItem value='Uzbekistan'>Uzbekistan</MenuItem>
            <MenuItem value='Venezuela'>Venezuela</MenuItem>
            <MenuItem value='Vietnam'>Vietnam</MenuItem>
            <MenuItem value='Virgin Islands (UK)'>Virgin Islands (UK)</MenuItem>
            <MenuItem value='Virgin Islands (US)'>Virgin Islands (US)</MenuItem>
            <MenuItem value='Yemen'>Yemen</MenuItem>
            <MenuItem value='Zambia'>Zambia</MenuItem>
            <MenuItem value='Zimbabwe'>Zimbabwe</MenuItem>

        </Select>
    )
}