import { MenuItem, Select } from "@mui/material"

export default function GetCountryList(props: any) {


    return (
        <Select
            fullWidth
            placeholder='Country'
            label='Article Country'
            labelId='Country'
            defaultValue={props.country}
            onChange={e => { props.setCountry(e.target.value) }}
        >
            <MenuItem value='2004'>Afghanistan</MenuItem>
            <MenuItem value='2008'>Albania</MenuItem>
            <MenuItem value='2010'>Antarctica</MenuItem>
            <MenuItem value='2012'>Algeria</MenuItem>
            <MenuItem value='2016'>American Samoa</MenuItem>
            <MenuItem value='2020'>Andorra</MenuItem>
            <MenuItem value='2024'>Angola</MenuItem>
            <MenuItem value='2028'>Antigua and Barbuda</MenuItem>
            <MenuItem value='2031'>Azerbaijan</MenuItem>
            <MenuItem value='2032'>Argentina</MenuItem>
            <MenuItem value='2036'>Australia</MenuItem>
            <MenuItem value='2040'>Austria</MenuItem>
            <MenuItem value='2044'>The Bahamas</MenuItem>
            <MenuItem value='2048'>Bahrain</MenuItem>
            <MenuItem value='2050'>Bangladesh</MenuItem>
            <MenuItem value='2051'>Armenia</MenuItem>
            <MenuItem value='2052'>Barbados</MenuItem>
            <MenuItem value='2056'>Belgium</MenuItem>
            <MenuItem value='2060'>Bermuda</MenuItem>
            <MenuItem value='2064'>Bhutan</MenuItem>
            <MenuItem value='2068'>Bolivia</MenuItem>
            <MenuItem value='2070'>Bosnia and Herzegovina</MenuItem>
            <MenuItem value='2072'>Botswana</MenuItem>
            <MenuItem value='2074'>Bouvet Island</MenuItem>
            <MenuItem value='2076'>Brazil</MenuItem>
            <MenuItem value='2084'>Belize</MenuItem>
            <MenuItem value='2086'>British Indian Ocean Territory</MenuItem>
            <MenuItem value='2090'>Solomon Islands</MenuItem>
            <MenuItem value='2092'>British Virgin Islands</MenuItem>
            <MenuItem value='2096'>Brunei</MenuItem>
            <MenuItem value='2100'>Bulgaria</MenuItem>
            <MenuItem value='2104'>Myanmar (Burma)</MenuItem>
            <MenuItem value='2108'>Burundi</MenuItem>
            <MenuItem value='2112'>Belarus</MenuItem>
            <MenuItem value='2116'>Cambodia</MenuItem>
            <MenuItem value='2120'>Cameroon</MenuItem>
            <MenuItem value='2124'>Canada</MenuItem>
            <MenuItem value='2132'>Cabo Verde</MenuItem>
            <MenuItem value='2136'>Cayman Islands</MenuItem>
            <MenuItem value='2140'>Central African Republic</MenuItem>
            <MenuItem value='2144'>Sri Lanka</MenuItem>
            <MenuItem value='2148'>Chad</MenuItem>
            <MenuItem value='2152'>Chile</MenuItem>
            <MenuItem value='2156'>China</MenuItem>
            <MenuItem value='2158'>Taiwan</MenuItem>
            <MenuItem value='2162'>Christmas Island</MenuItem>
            <MenuItem value='2166'>Cocos (Keeling) Islands</MenuItem>
            <MenuItem value='2170'>Colombia</MenuItem>
            <MenuItem value='2174'>Comoros</MenuItem>
            <MenuItem value='2175'>Mayotte</MenuItem>
            <MenuItem value='2178'>Republic of the Congo</MenuItem>
            <MenuItem value='2180'>Democratic Republic of the Congo</MenuItem>
            <MenuItem value='2184'>Cook Islands</MenuItem>
            <MenuItem value='2188'>Costa Rica</MenuItem>
            <MenuItem value='2191'>Croatia</MenuItem>
            <MenuItem value='2196'>Cyprus</MenuItem>
            <MenuItem value='2203'>Czechia</MenuItem>
            <MenuItem value='2204'>Benin</MenuItem>
            <MenuItem value='2208'>Denmark</MenuItem>
            <MenuItem value='2212'>Dominica</MenuItem>
            <MenuItem value='2214'>Dominican Republic</MenuItem>
            <MenuItem value='2218'>Ecuador</MenuItem>
            <MenuItem value='2222'>El Salvador</MenuItem>
            <MenuItem value='2226'>Equatorial Guinea</MenuItem>
            <MenuItem value='2231'>Ethiopia</MenuItem>
            <MenuItem value='2232'>Eritrea</MenuItem>
            <MenuItem value='2233'>Estonia</MenuItem>
            <MenuItem value='2234'>Faroe Islands</MenuItem>
            <MenuItem value='2238'>Falkland Islands (Islas Malvinas)</MenuItem>
            <MenuItem value='2239'>South Georgia and the South Sandwich Islands</MenuItem>
            <MenuItem value='2242'>Fiji</MenuItem>
            <MenuItem value='2246'>Finland</MenuItem>
            <MenuItem value='2250'>France</MenuItem>
            <MenuItem value='2254'>French Guiana</MenuItem>
            <MenuItem value='2258'>French Polynesia</MenuItem>
            <MenuItem value='2260'>French Southern and Antarctic Lands</MenuItem>
            <MenuItem value='2262'>Djibouti</MenuItem>
            <MenuItem value='2266'>Gabon</MenuItem>
            <MenuItem value='2268'>Georgia</MenuItem>
            <MenuItem value='2270'>The Gambia</MenuItem>
            <MenuItem value='2275'>Palestine</MenuItem>
            <MenuItem value='2276'>Germany</MenuItem>
            <MenuItem value='2288'>Ghana</MenuItem>
            <MenuItem value='2292'>Gibraltar</MenuItem>
            <MenuItem value='2296'>Kiribati</MenuItem>
            <MenuItem value='2300'>Greece</MenuItem>
            <MenuItem value='2304'>Greenland</MenuItem>
            <MenuItem value='2308'>Grenada</MenuItem>
            <MenuItem value='2312'>Guadeloupe</MenuItem>
            <MenuItem value='2316'>Guam</MenuItem>
            <MenuItem value='2320'>Guatemala</MenuItem>
            <MenuItem value='2324'>Guinea</MenuItem>
            <MenuItem value='2328'>Guyana</MenuItem>
            <MenuItem value='2332'>Haiti</MenuItem>
            <MenuItem value='2334'>Heard Island and McDonald Islands</MenuItem>
            <MenuItem value='2336'>Vatican City</MenuItem>
            <MenuItem value='2340'>Honduras</MenuItem>
            <MenuItem value='2344'>Hong Kong</MenuItem>
            <MenuItem value='2348'>Hungary</MenuItem>
            <MenuItem value='2352'>Iceland</MenuItem>
            <MenuItem value='2356'>India</MenuItem>
            <MenuItem value='2360'>Indonesia</MenuItem>
            <MenuItem value='2368'>Iraq</MenuItem>
            <MenuItem value='2372'>Ireland</MenuItem>
            <MenuItem value='2376'>Israel</MenuItem>
            <MenuItem value='2380'>Italy</MenuItem>
            <MenuItem value='2384'>Cote d'Ivoire</MenuItem>
            <MenuItem value='2388'>Jamaica</MenuItem>
            <MenuItem value='2392'>Japan</MenuItem>
            <MenuItem value='2398'>Kazakhstan</MenuItem>
            <MenuItem value='2400'>Jordan</MenuItem>
            <MenuItem value='2404'>Kenya</MenuItem>
            <MenuItem value='2410'>South Korea</MenuItem>
            <MenuItem value='2414'>Kuwait</MenuItem>
            <MenuItem value='2417'>Kyrgyzstan</MenuItem>
            <MenuItem value='2418'>Laos</MenuItem>
            <MenuItem value='2422'>Lebanon</MenuItem>
            <MenuItem value='2426'>Lesotho</MenuItem>
            <MenuItem value='2428'>Latvia</MenuItem>
            <MenuItem value='2430'>Liberia</MenuItem>
            <MenuItem value='2434'>Libya</MenuItem>
            <MenuItem value='2438'>Liechtenstein</MenuItem>
            <MenuItem value='2440'>Lithuania</MenuItem>
            <MenuItem value='2442'>Luxembourg</MenuItem>
            <MenuItem value='2446'>Macao</MenuItem>
            <MenuItem value='2450'>Madagascar</MenuItem>
            <MenuItem value='2454'>Malawi</MenuItem>
            <MenuItem value='2458'>Malaysia</MenuItem>
            <MenuItem value='2462'>Maldives</MenuItem>
            <MenuItem value='2466'>Mali</MenuItem>
            <MenuItem value='2470'>Malta</MenuItem>
            <MenuItem value='2474'>Martinique</MenuItem>
            <MenuItem value='2478'>Mauritania</MenuItem>
            <MenuItem value='2480'>Mauritius</MenuItem>
            <MenuItem value='2484'>Mexico</MenuItem>
            <MenuItem value='2492'>Monaco</MenuItem>
            <MenuItem value='2496'>Mongolia</MenuItem>
            <MenuItem value='2498'>Moldova</MenuItem>
            <MenuItem value='2499'>Montenegro</MenuItem>
            <MenuItem value='2500'>Montserrat</MenuItem>
            <MenuItem value='2504'>Morocco</MenuItem>
            <MenuItem value='2508'>Mozambique</MenuItem>
            <MenuItem value='2512'>Oman</MenuItem>
            <MenuItem value='2516'>Namibia</MenuItem>
            <MenuItem value='2520'>Nauru</MenuItem>
            <MenuItem value='2524'>Nepal</MenuItem>
            <MenuItem value='2528'>Netherlands</MenuItem>
            <MenuItem value='2531'>Curacao</MenuItem>
            <MenuItem value='2533'>Aruba</MenuItem>
            <MenuItem value='2534'>Sint Maarten</MenuItem>
            <MenuItem value='2535'>Caribbean Netherlands</MenuItem>
            <MenuItem value='2540'>New Caledonia</MenuItem>
            <MenuItem value='2548'>Vanuatu</MenuItem>
            <MenuItem value='2554'>New Zealand</MenuItem>
            <MenuItem value='2558'>Nicaragua</MenuItem>
            <MenuItem value='2562'>Niger</MenuItem>
            <MenuItem value='2566'>Nigeria</MenuItem>
            <MenuItem value='2570'>Niue</MenuItem>
            <MenuItem value='2574'>Norfolk Island</MenuItem>
            <MenuItem value='2578'>Norway</MenuItem>
            <MenuItem value='2580'>Northern Mariana Islands</MenuItem>
            <MenuItem value='2581'>United States Minor Outlying Islands</MenuItem>
            <MenuItem value='2583'>Micronesia</MenuItem>
            <MenuItem value='2584'>Marshall Islands</MenuItem>
            <MenuItem value='2585'>Palau</MenuItem>
            <MenuItem value='2586'>Pakistan</MenuItem>
            <MenuItem value='2591'>Panama</MenuItem>
            <MenuItem value='2598'>Papua New Guinea</MenuItem>
            <MenuItem value='2600'>Paraguay</MenuItem>
            <MenuItem value='2604'>Peru</MenuItem>
            <MenuItem value='2608'>Philippines</MenuItem>
            <MenuItem value='2612'>Pitcairn Islands</MenuItem>
            <MenuItem value='2616'>Poland</MenuItem>
            <MenuItem value='2620'>Portugal</MenuItem>
            <MenuItem value='2624'>Guinea-Bissau</MenuItem>
            <MenuItem value='2626'>Timor-Leste</MenuItem>
            <MenuItem value='2630'>Puerto Rico</MenuItem>
            <MenuItem value='2634'>Qatar</MenuItem>
            <MenuItem value='2638'>Reunion</MenuItem>
            <MenuItem value='2642'>Romania</MenuItem>
            <MenuItem value='2643'>Russia</MenuItem>
            <MenuItem value='2646'>Rwanda</MenuItem>
            <MenuItem value='2652'>Saint Barthelemy</MenuItem>
            <MenuItem value='2654'>Saint Helena, Ascension and Tristan da Cunha</MenuItem>
            <MenuItem value='2659'>Saint Kitts and Nevis</MenuItem>
            <MenuItem value='2660'>Anguilla</MenuItem>
            <MenuItem value='2662'>Saint Lucia</MenuItem>
            <MenuItem value='2663'>Saint Martin</MenuItem>
            <MenuItem value='2666'>Saint Pierre and Miquelon</MenuItem>
            <MenuItem value='2670'>Saint Vincent and the Grenadines</MenuItem>
            <MenuItem value='2674'>San Marino</MenuItem>
            <MenuItem value='2678'>Sao Tome and Principe</MenuItem>
            <MenuItem value='2682'>Saudi Arabia</MenuItem>
            <MenuItem value='2686'>Senegal</MenuItem>
            <MenuItem value='2688'>Serbia</MenuItem>
            <MenuItem value='2690'>Seychelles</MenuItem>
            <MenuItem value='2694'>Sierra Leone</MenuItem>
            <MenuItem value='2702'>Singapore</MenuItem>
            <MenuItem value='2703'>Slovakia</MenuItem>
            <MenuItem value='2704'>Vietnam</MenuItem>
            <MenuItem value='2705'>Slovenia</MenuItem>
            <MenuItem value='2706'>Somalia</MenuItem>
            <MenuItem value='2710'>South Africa</MenuItem>
            <MenuItem value='2716'>Zimbabwe</MenuItem>
            <MenuItem value='2724'>Spain</MenuItem>
            <MenuItem value='2728'>South Sudan</MenuItem>
            <MenuItem value='2732'>Western Sahara</MenuItem>
            <MenuItem value='2736'>Sudan</MenuItem>
            <MenuItem value='2740'>Suriname</MenuItem>
            <MenuItem value='2744'>Svalbard and Jan Mayen</MenuItem>
            <MenuItem value='2748'>Eswatini</MenuItem>
            <MenuItem value='2752'>Sweden</MenuItem>
            <MenuItem value='2756'>Switzerland</MenuItem>
            <MenuItem value='2762'>Tajikistan</MenuItem>
            <MenuItem value='2764'>Thailand</MenuItem>
            <MenuItem value='2768'>Togo</MenuItem>
            <MenuItem value='2772'>Tokelau</MenuItem>
            <MenuItem value='2776'>Tonga</MenuItem>
            <MenuItem value='2780'>Trinidad and Tobago</MenuItem>
            <MenuItem value='2784'>United Arab Emirates</MenuItem>
            <MenuItem value='2788'>Tunisia</MenuItem>
            <MenuItem value='2792'>Turkiye</MenuItem>
            <MenuItem value='2795'>Turkmenistan</MenuItem>
            <MenuItem value='2796'>Turks and Caicos Islands</MenuItem>
            <MenuItem value='2798'>Tuvalu</MenuItem>
            <MenuItem value='2800'>Uganda</MenuItem>
            <MenuItem value='2804'>Ukraine</MenuItem>
            <MenuItem value='2807'>North Macedonia</MenuItem>
            <MenuItem value='2818'>Egypt</MenuItem>
            <MenuItem value='2826'>United Kingdom</MenuItem>
            <MenuItem value='2831'>Guernsey</MenuItem>
            <MenuItem value='2832'>Jersey</MenuItem>
            <MenuItem value='2833'>Isle of Man</MenuItem>
            <MenuItem value='2834'>Tanzania</MenuItem>
            <MenuItem value='2840'>United States</MenuItem>
            <MenuItem value='2850'>U.S. Virgin Islands</MenuItem>
            <MenuItem value='2854'>Burkina Faso</MenuItem>
            <MenuItem value='2858'>Uruguay</MenuItem>
            <MenuItem value='2860'>Uzbekistan</MenuItem>
            <MenuItem value='2862'>Venezuela</MenuItem>
            <MenuItem value='2876'>Wallis and Futuna</MenuItem>
            <MenuItem value='2882'>Samoa</MenuItem>
            <MenuItem value='2887'>Yemen</MenuItem>
            <MenuItem value='2894'>Zambia</MenuItem>
            <MenuItem value='2900'>Kosovo</MenuItem>
        </Select>
    )
}